### ISSUE TITLE
Generate an OpenSSH keypair FAILED

### ISSUE THREAD

**Issue by emoxam** [3DRaven/pi-hole2vpn#3]
TASK [user_creation : Generate an OpenSSH keypair to path /home/emoxam/.ssh/id_rsa_vpn] *************************************************************************************************************************
fatal: [5.61.34.58 -> localhost]: FAILED! => {"changed": false, "msg": "The directory /home/emoxam/.ssh does not exist or the file is not a directory", "name": "/home/emoxam/.ssh"}

Why is it failed ?

**Comment by 3DRaven** [comment]
You must set full path with key name for ssh key generation. Not just path.

**Comment by emoxam** [comment]
i must create the emoxam user at the host with ansible for some reason.

**Comment by 3DRaven** [comment]
Can you explain your concern deeply?
