### ISSUE TITLE
Error starting project 500 Server Error for http+docker

### ISSUE THREAD

**Issue by emoxam** [3DRaven/pi-hole2vpn#4]
TASK [pi_hole_install : Start new pihole container] *************************************************************************************************************************************************************
fatal: [5.61.34.58]: FAILED! => {"changed": false, "errors": [], "module_stderr": "", "module_stdout": "", "msg": "Error starting project 500 Server Error for http+docker://localhost/v1.43/images/create?tag=latest&fromImage=pihole%2Fpihole: Internal Server Error (\"Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address\")"}

**Comment by 3DRaven** [comment]
It is because ipv6 totally disabled in this playbook. I do not use it. If you want, you can fix it. Sorry.
